// The official SL2 rulebook, transcribed from SL2_Rulebook.pdf (Kasim Vadiwala, Sep 20 2026).
// Lives here as plain data (not in Supabase) because it changes rarely, must render fully
// offline, and needs to be searchable/highlightable — a hand-structured block format gives
// exact control over both of those without pulling in a markdown parser. To publish a new
// version of the rulebook: edit the sections below and bump RULEBOOK_VERSION/RULEBOOK_UPDATED.
export const RULEBOOK_VERSION = '1.0'
export const RULEBOOK_UPDATED = 'Sep 20, 2026'
export const RULEBOOK_AUTHOR = 'Kasim Vadiwala'

// Block types: p (paragraph), h (sub-heading), ul/ol (lists), table ({headers, rows}),
// note (callout), flow (the slot-structure diagram). Paragraph/list/table text supports
// **bold** and is what search matches/highlights against.
export const RULEBOOK_SECTIONS = [
  {
    id: 'league-format',
    number: 1,
    title: 'League format',
    blocks: [
      { t: 'p', text: 'SL2 is a 9-a-side underarm turf cricket league contested by 7 teams, played in tri-series slots.' },
      { t: 'p', text: 'A **slot** brings 3 teams together for 6 matches in a single session. Each slot is a self-contained mini-tournament with its own winner. The league stage has 21 slots; each team appears in 9 of them.' },
      { t: 'p', text: 'Slots are played on Mondays and Thursdays through mid-December.' },
      { t: 'h', text: 'Playoffs' },
      { t: 'ul', items: [
        'Teams placed 6th and 7th at the end of the league stage are eliminated.',
        'The semi-final is a tri-series slot between the teams placed 3rd, 4th and 5th.',
        'The winner of that slot joins the 1st and 2nd placed teams in the final, also played as a tri-series slot.',
      ] },
    ],
  },
  {
    id: 'match-format',
    number: 2,
    title: 'Match format',
    blocks: [
      { t: 'table', headers: ['Item', 'Rule'], rows: [
        ['Overs per innings', '7'],
        ['Players per side', '9'],
        ['Ball', 'Plain tennis ball'],
        ['Maximum overs per bowler', '1'],
        ['Ground', 'Fully enclosed cage (side nets and roof net)'],
      ] },
      { t: 'p', text: 'A 1-over cap means at least 7 of the 9 players must bowl. Teams should pick accordingly.' },
      { t: 'h', text: 'Start times' },
      { t: 'p', text: 'Matches begin as scheduled. A team whose players are late starts short. The schedule is never altered to accommodate late arrivals.' },
      { t: 'h', text: 'Short teams' },
      { t: 'p', text: 'A team may start with however many players it has. If it has fewer than 7 available bowlers, the captain nominates which bowler repeats an over so that all 7 overs are bowled. A player who has bowled two overs in one match may not do so again in any other match of that slot — the repeat must be rotated.' },
      { t: 'h', text: 'Late arrivals' },
      { t: 'p', text: 'A player arriving after the match has started may join only at the end of the current over. He then has full rights — he may bat and bowl normally, subject to the all-rounder restrictions below.' },
      { t: 'h', text: 'Batting short' },
      { t: 'p', text: 'When a side runs out of partners, the last batsman bats alone. He runs a single end and every run counts normally, odd or even. He retains the strike for every delivery.' },
      { t: 'h', text: 'All-rounder restrictions' },
      { t: 'p', text: 'The shorter the match, the more the roles are separated.' },
      { t: 'table', headers: ['Match length', 'Restriction'], rows: [
        ['7 overs', 'The opening batting pair may not bowl. Bowlers may not bat at No. 1 or No. 2.'],
        ['6 overs', 'The top 3 batsmen may not bowl. Bowlers may not bat at No. 1, No. 2 or No. 3.'],
        ['5 overs or fewer', 'No restriction. Anyone may bat anywhere and anyone may bowl.'],
      ] },
      { t: 'h', text: 'Equipment' },
      { t: 'p', text: 'Turf shoes only — spikes and metal studs are not permitted on the turf. Bats must be **wooden**. Fibre bats and bats of any other material are not allowed.' },
      { t: 'p', text: 'Restrictions apply to **batting positions, not named players**. In a 7-over match the restriction covers positions 1 and 2; in a 6-over match, positions 1 to 3. Whoever walks in at those positions is bound by it, however the order is rearranged during the innings.' },
      { t: 'p', text: 'The restriction is fixed by the match length as it starts, so a match reduced in length after it begins keeps the restriction it started under.' },
    ],
  },
  {
    id: 'delivery-pace-rule',
    number: 3,
    title: 'The delivery and the pace rule',
    blocks: [
      { t: 'p', text: "A delivery is legal only if the ball is released **below the bowler's waist**." },
      { t: 'h', text: 'Release above the waist' },
      { t: 'p', text: 'The first such release brings a warning to the bowler. That warning carries for the **entire slot**, and a second instance is a no-ball. If the umpire judges even the first release to be far above the waist — beyond what a warning covers — he may call a no-ball immediately.' },
      { t: 'h', text: 'Pace is appeal-driven' },
      { t: 'p', text: 'The umpire does not police pace on every ball. The batsman must appeal.' },
      { t: 'ol', items: [
        'If the batsman feels a delivery was excessively fast, he appeals to the umpire immediately.',
        'If the umpire agrees, he may either call a no-ball or issue a warning to the bowler.',
        'If the batsman appeals again in the same over and the umpire agrees, the delivery is a no-ball.',
        '**No free hit is awarded for a pace no-ball.**',
      ] },
      { t: 'p', text: 'A warning applies within the over only. A bowler who returns for a later over starts with a clean slate. (This arises only when a captain has nominated a bowler to repeat an over under the short-team rule.)' },
      { t: 'p', text: 'Only the striker may appeal. The non-striker has no say, in line with section 12.' },
      { t: 'p', text: 'The umpire judges severity. If he considers the delivery extremely paced he calls a no-ball, and any dismissal off it is cancelled — the batsman continues. If he considers it only warning-worthy, the bowler is warned and the dismissal stands. The appeal must be made immediately, before the next delivery.' },
    ],
  },
  {
    id: 'wides-no-balls-free-hits',
    number: 4,
    title: 'Wides, no-balls and free hits',
    blocks: [
      { t: 'p', text: 'A wide or no-ball costs **1 run and is re-bowled**.' },
      { t: 'p', text: 'Wides are judged against marked lines on the pitch, on both the off side and the leg side. The wide is judged from where the batsman originally stood, not from where he has moved to.' },
      { t: 'h', text: 'A delivery is a no-ball if:' },
      { t: 'ul', items: [
        'the bowler oversteps the crease;',
        "the ball is released above the bowler's waist, on the second instance in a slot or at the umpire's discretion on the first (section 3);",
        'the ball reaches the batsman as a full toss above his waist height;',
        'the bowler breaks the fielding restriction (section 6);',
        "the bowler hits the stumps at the bowler's end with his hand while delivering;",
        'the bowler attempts a Mankad while the batsman is inside his crease.',
      ] },
      { t: 'p', text: 'Free hits are awarded for every no-ball except a pace no-ball. On a free hit the batsman can be dismissed **run out only**.' },
      { t: 'p', text: "There is no height limit on a delivery that has bounced. A ball passing above the batsman's shoulder or head off the pitch is legal. Only a **full toss above waist height** is a no-ball." },
    ],
  },
  {
    id: 'boundaries-cage',
    number: 5,
    title: 'Boundaries and the cage',
    blocks: [
      { t: 'p', text: 'The nets are live playing surfaces. The ball remains in play after striking any net, and both catches and run-outs off a rebound are valid.' },
      { t: 'table', headers: ['Ball strikes', 'Result'], rows: [
        ['Straight net facing the batsman, on the full', 'Six, dead ball immediately — no catch possible'],
        ['Side net, on the full, then caught', 'Out'],
        ['Side net, on the full, not caught', 'Ball live; 4 if it reaches the boundary'],
        ['Roof net, then caught', 'Out'],
        ['Roof net, not caught', 'Ball live; 4 if it reaches the boundary'],
        ['Roof net first, then the straight net', 'Not a six — maximum 4, or run runs'],
        ['Back net behind the keeper, on the full', 'Run runs only, ball live'],
      ] },
      { t: 'p', text: 'The roof caps the value of a shot but never kills it. A ball that touches the roof can still be caught for a dismissal and can still reach the boundary for 4, but it can never be a six.' },
    ],
  },
  {
    id: 'fielding-restrictions',
    number: 6,
    title: 'Fielding restrictions',
    blocks: [
      { t: 'p', text: 'The fielding side must be distributed across marked zones as follows:' },
      { t: 'table', headers: ['Zone', 'Maximum fielders'], rows: [
        ['On the boundary net', '3'],
        ['Mid area', '2'],
        ['In front of the stumps', '2'],
        ['Bowler', '1'],
        ['Wicketkeeper', '1'],
      ] },
      { t: 'p', text: 'A breach is a no-ball.' },
      { t: 'p', text: 'The zones must be physically marked on the turf before play. The restriction is judged **at the moment of release**; once the ball is released fielders may move freely.' },
      { t: 'h', text: 'Short sides' },
      { t: 'p', text: "A team fielding fewer than 9 players is not bound by the zone table. Its only restriction is that **no more than 5 fielders may be placed behind the bowler** — that is, beyond the bowler's stumps toward the straight net, judged at the moment of release. The captain is otherwise free to set the field as he wishes." },
    ],
  },
  {
    id: 'dismissals',
    number: 7,
    title: 'Dismissals',
    blocks: [
      { t: 'h', text: 'Mankad' },
      { t: 'p', text: 'If the non-striker is out of his crease at the point of delivery, he is out immediately. No warning is required. If he is inside his crease, the attempt is a no-ball.' },
      { t: 'h', text: 'Catches off the nets' },
      { t: 'p', text: 'Valid off the side nets and the roof net. Not possible off the straight net, where a shot on the full is an immediate six.' },
      { t: 'h', text: 'Free hit' },
      { t: 'p', text: 'Run out only.' },
      { t: 'h', text: 'Retirement' },
      { t: 'p', text: 'There is no retired hurt in SL2 — every retirement is a retirement out. A batsman who cannot continue, or whom his captain wishes to replace because he is out of form, must dismiss himself by hit wicket. It counts as a wicket against the batting side, but is recorded as **retired out** with no bowler credited.' },
      { t: 'h', text: 'Runners' },
      { t: 'p', text: 'A side may use only one runner per innings. Once any batsman has taken a runner, no other batsman in that innings may have one, including for a genuine injury.' },
    ],
  },
  {
    id: 'squads-guests-eligibility',
    number: 8,
    title: 'Squads, guests and eligibility',
    blocks: [
      { t: 'p', text: 'Every player has one **parent team** — the team that bought him at auction. He may also turn out as a guest for another team to fill its squad.' },
      { t: 'p', text: 'When a squad player is unavailable, the captain may replace him by picking, in this order of preference:' },
      { t: 'ol', items: [
        'a player from a team not playing that slot, of the **same category or lower**;',
        'failing that, a player from the **unreserved list** — players not registered for or participating in the league — again of the same category or lower.',
      ] },
      { t: 'h', text: 'Limits and procedure' },
      { t: 'ul', items: [
        'A maximum of **2 guest players** per team in a slot. This applies in the semi-final and final slots too.',
        'Guests must be declared to the umpire and the opposition before the toss.',
        'A player may not guest in a slot in which his parent team is playing.',
      ] },
      { t: 'h', text: 'Stats and rewards' },
      { t: 'p', text: "A guest innings is scored under the name of the player being replaced, and those runs and wickets go to that player's season record. Slot rewards for the performance go to the guest who actually played." },
      { t: 'note', text: 'This is a deliberate league rule, not a scoring error, and is published here so that it is understood and agreed by all owners in advance.' },
    ],
  },
  {
    id: 'slot-structure-bonus-runs',
    number: 9,
    title: 'Slot structure and bonus runs',
    blocks: [
      { t: 'p', text: 'Each slot is 6 matches: a 3-match round robin followed by a 3-match playoff.' },
      { t: 'p', text: 'Every match begins with a normal toss, including the qualifier, eliminator and final. Seeding carries a run advantage, never a choice of innings.' },
      { t: 'flow' },
      { t: 'h', text: 'Matches 1–3' },
      { t: 'p', text: 'Each team plays the other two once. Teams are then seeded 1st, 2nd and 3rd. Where teams are level on wins — including the common case of all three winning one each — seeding is decided by **net run rate within the slot**.' },
      { t: 'h', text: 'Match 4 — Qualifier' },
      { t: 'p', text: '1st v 2nd. The 1st-placed team receives a **10-run advantage**. The winner goes to the final.' },
      { t: 'h', text: 'Match 5 — Eliminator' },
      { t: 'p', text: 'The losing qualifier v 3rd. The losing qualifier receives a **10-run advantage**.' },
      { t: 'h', text: 'Match 6 — Final' },
      { t: 'p', text: 'Qualifier winner v Eliminator winner.' },
      { t: 'h', text: 'How the 10 runs apply' },
      { t: 'p', text: 'If the advantaged team bats first, 10 runs are added to its score. If it bats second, the team batting first starts on minus 10.' },
      { t: 'h', text: 'Ties' },
      { t: 'p', text: 'A tie in the qualifier, eliminator or final is decided by a super over.' },
      { t: 'ul', items: [
        'The bowler is nominated before the super over begins and may be any player, including one who has already bowled in the match.',
        'The batting side nominates 3 batsmen. The innings ends at 2 wickets.',
        'A tied super over is decided by countback on the main match innings, in this order: most boundaries, then most sixes, then the highest individual score, then the highest wicket-taker. The super over itself is excluded from the count.',
      ] },
      { t: 'p', text: 'Bonus and penalty runs are recorded as a separate line item and are not attributed to any batsman. They do count toward the final scoreline, and therefore toward both net run rate and margin bonuses.' },
      { t: 'p', text: 'A net score may fall below zero. If a side finishes on a negative total, the chasing side wins immediately without batting, and earns the **+2 margin bonus**. For net run rate the winners are credited with the opposition\'s **gross** score — the runs actually scored before the penalty — over **1 over faced**.' },
      { t: 'h', text: '1st place advantage in the Final Slot' },
      { t: 'p', text: 'The teams finishing 1st and 2nd in the league stage qualify directly for the Final Slot. The team finishing 1st carries an additional advantage into it.' },
      { t: 'ul', items: [
        'The 1st placed team holds a **10-run bonus**, usable in any **one** match of the Final Slot.',
        'It may be used in the matches leading up to the Final, **but not in the Final itself**.',
        'The team must inform the Match Referee **before the match starts** if it wishes to use the bonus.',
        'Once a single ball has been bowled, the bonus can no longer be activated for that match.',
        'If the team does not use it before a match begins, it stays available for the next eligible match.',
        'The bonus can be used **once only** and cannot be carried beyond the Final Slot.',
      ] },
      { t: 'note', text: 'The two advantages stack. If the 1st placed team also finishes top of the Final Slot round robin, it receives the standard 10-run qualifier advantage and may additionally activate its saved bonus in the same match. This is intended.' },
    ],
  },
  {
    id: 'points-standings',
    number: 10,
    title: 'Points and standings',
    blocks: [
      { t: 'p', text: 'Points are earned for **slot placing**, not for individual matches.' },
      { t: 'table', headers: ['Slot result', 'Points'], rows: [
        ['Slot winner', '4'],
        ['Runner-up (final loser)', '2'],
        ['Third', '0'],
        ['Punctuality bonus (section 11)', '1'],
      ] },
      { t: 'p', text: 'A team plays 9 slots, so the maximum available from placings is 36, plus up to 9 punctuality points.' },
      { t: 'h', text: 'Bonus points for margin' },
      { t: 'p', text: 'Teams earn additional points for dominant wins. These go to the **main league table only**, not to the slot table.' },
      { t: 'table', headers: ['Achievement', 'Bonus'], rows: [
        ['Defends a target by 30 or more runs, or chases in 4 overs or fewer', '+1'],
        ['Defends a target by 60 or more runs, or chases in 2 overs or fewer', '+2'],
      ] },
      { t: 'p', text: 'The tiers do not stack — a win clearing both bars earns +2 only. Margin bonuses are available in all 6 matches of a slot, including the qualifier, eliminator and final.' },
      { t: 'p', text: 'Margin is measured on the final scoreline as it stands, so bonus and penalty runs count toward it. Margin bonuses are available only in **full 7-over matches** — a shortened match earns none.' },
      { t: 'h', text: 'Walkover' },
      { t: 'p', text: 'If a team fails to appear, its opponents receive the points. Net run rate is unaffected.' },
      { t: 'h', text: 'Abandoned slots' },
      { t: 'p', text: 'Where rain or bad weather prevents play, the three captains decide between them whether the slot goes ahead. A slot not played carries **6 points in total**.' },
      { t: 'ul', items: [
        'If all three teams mutually agree not to play, to avoid injuries, the 6 points are divided equally — 2 each. No punctuality bonus is awarded.',
        'If one team is willing to play and the other two are not, the willing team is awarded all 6 points.',
        'If two teams are willing and one is not, the two play each other. The winner takes 4 points and the loser 2. The team that declined gets nothing.',
      ] },
      { t: 'p', text: 'A team claiming points as the willing side must actually take the field. Stating a willingness to play is not enough.' },
      { t: 'p', text: 'A slot abandoned partway falls under this rule in full. Matches already completed are set aside and the 6 points are allocated as above.' },
      { t: 'h', text: 'Tied league match' },
      { t: 'p', text: 'Points are split. This applies to the 3 round-robin matches; playoff ties go to a super over.' },
      { t: 'h', text: 'Table tiebreak' },
      { t: 'p', text: 'Teams level on total points at the end of the league stage are separated by **net run rate across the season**.' },
      { t: 'h', text: 'Individual season awards' },
      { t: 'p', text: 'Batting is decided on most runs, with highest average as the tiebreak. Bowling is decided on most wickets, with lowest average as the tiebreak. There is no minimum number of appearances to qualify.' },
    ],
  },
  {
    id: 'punctuality-bonus',
    number: 11,
    title: 'Time and the punctuality bonus',
    blocks: [
      { t: 'p', text: 'Each slot of 6 matches is allocated **3 hours** in total, running from **9:00 pm to 12:00 am**.' },
      { t: 'p', text: 'If the slot finishes on or before time, **all three teams receive 1 bonus point** toward the main league table.' },
      { t: 'p', text: 'The bonus is awarded only if **all 6 matches were started as full 7-over contests**. If any match was shortened, no bonus is awarded even if the slot finishes on time.' },
      { t: 'p', text: 'The bonus is collective by design: all three teams share an interest in keeping the session moving.' },
      { t: 'note', text: 'Nothing is deducted. This is a bonus-only rule: if the slot overruns or fails to finish on time, none of the three teams receives the bonus point, and no team is penalised beyond that.' },
      { t: 'p', text: 'Where a delay is outside everyone\'s control — floodlight failure, rain, a double-booked cage — the Match Referee decides whether the bonus still stands.' },
    ],
  },
  {
    id: 'umpiring-conduct',
    number: 12,
    title: 'Umpiring and conduct',
    blocks: [
      { t: 'p', text: 'Matches are officiated by a **neutral appointed umpire**. The umpire decides overs reduction in a shortened match on the spot.' },
      { t: 'h', text: 'Match Referee' },
      { t: 'p', text: 'The referee for a slot is any member of the 5-person managing committee — **Kasim, Fajja, John, Kesur and Abhi Doshi** — or anyone the committee appoints for that slot.' },
      { t: 'h', text: 'Who may be on the turf' },
      { t: 'p', text: 'During a match the turf is limited to the fielding side, the two batsmen plus a runner if one is in use, 1 scorer, 1 Match Referee, 2 umpires and 1 commentator. Members of the resting team may not enter the turf.' },
      { t: 'h', text: 'Who may speak to the umpire' },
      { t: 'p', text: 'Only the batsman on strike and the fielding captain. Any other player from any participating team who approaches the umpire concedes **5 penalty runs** to the opposition. A member of the resting team who enters the turf concedes 5 penalty runs in his own team\'s next match.' },
      { t: 'h', text: 'Reviews' },
      { t: 'p', text: "A captain or batsman may review an umpire's decision on a **pace-related no-ball only**. No other decision is reviewable. The Match Referee answers the review and his call is final. Each side has **one review per innings**; a successful review is retained, an unsuccessful one is lost." },
      { t: 'p', text: 'Both sides may review: the batting side against a rejected pace appeal, the fielding side against a pace no-ball that was given.' },
      { t: 'h', text: 'Conduct' },
      { t: 'p', text: 'Abuse of or dissent toward the umpire is met with a warning, then a run penalty awarded to the opposition.' },
      { t: 'note', text: "Still to settle: the size of the run penalty, what a repeat offence brings, and who has final say when an umpire's decision is disputed by a captain." },
    ],
  },
  {
    id: 'open-items',
    number: 13,
    title: 'Open items',
    blocks: [
      { t: 'p', text: 'Nothing remains outstanding. Every rule discussed has been settled and written into the sections above.' },
      { t: 'p', text: 'Use this section to log questions raised by owners once the rulebook has been circulated.' },
      { t: 'table', headers: ['Raised by', 'Question', 'Status'], rows: [] },
    ],
  },
]
